name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Create google-services.json
      run: echo "{'project_info':{'project_number':'','project_id':''},'client':[{'client_info':{'mobilesdk_app_id':'1:111111111111:android:1111111111111111','android_client_info':{'package_name':'uk.co.cerihughes.mgm.android'}},'api_key':[{'current_key':'1'}]}]}" > app/google-services.json
    - name: Create secrets.xml
      run: echo "<resources><string name='google_maps_api_key'>1</string></resources>" > app/src/main/res/values/secrets.xml
    - name: Build with Gradle
      run: ./gradlew build test lint connectedCheck --warn
